export const WEBSITES_ITEMS = 'WEBSITES_ITEMS';
export const GAMES_ITEMS = 'GAMES_ITEMS';

export const CONTACT_REQUEST_START = 'CONTACT_REQUEST_START';
export const CONTACT_REQUEST_SUCCESS = 'CONTACT_REQUEST_SUCCESS';
export const CONTACT_REQUEST_FAIL = 'CONTACT_REQUEST_FAIL';